FROM node:lts-alpine

WORKDIR /app

# Copy only dependency files first (better caching)
COPY package.json package-lock.json* ./

RUN npm install

# Copy rest of the app
COPY . .

CMD ["npm", "start", "--", "--host", "0.0.0.0", "--port", "4200", "--disable-host-check"]