apiVersion: apps/v1
kind: Deployment

metadata:
  name: api-deployment

spec:
  replicas: 1

  selector:
    matchLabels:
      component: api

  template:
    metadata:
      labels:
        component: api

    spec:
      containers:
        - name: api
          image: akashhulke/api:ba2a0458685391c10b6183721c2ac105bcca524b

          ports:
            - containerPort: 5000