apiVersion: apps/v1
kind: Deployment

metadata:
  name: api-deployment

spec:
  replicas: 1

  selector:
    matchLabels:
      component: api

  template:
    metadata:
      labels:
        component: api

    spec:
      containers:
        - name: api
          image: akashhulke/api:40ae81ccdb80d841c8db6a7bd2423fec11dbfba7

          ports:
            - containerPort: 5000