apiVersion: apps/v1
kind: Deployment

metadata:
  name: api-deployment

spec:
  replicas: 1

  selector:
    matchLabels:
      component: api

  template:
    metadata:
      labels:
        component: api

    spec:
      containers:
        - name: api
          image: akashhulke/api:96f19d251f6b79e6430fa8ca3dbdc8a0bae9ff5e

          ports:
            - containerPort: 5000