apiVersion: apps/v1
kind: Deployment

metadata:
  name: client-deployment

spec:
  replicas: 1

  selector:
    matchLabels:
      component: client

  template:
    metadata:
      labels:
        component: client

    spec:
      containers:
        - name: client
          image: akashhulke/client:40ae81ccdb80d841c8db6a7bd2423fec11dbfba7
          ports:
            - containerPort: 3000