apiVersion: apps/v1
kind: Deployment

metadata:
  name: client-deployment

spec:
  replicas: 1

  selector:
    matchLabels:
      component: client

  template:
    metadata:
      labels:
        component: client

    spec:
      containers:
        - name: client
          image: akashhulke/client:96f19d251f6b79e6430fa8ca3dbdc8a0bae9ff5e
          ports:
            - containerPort: 3000