apiVersion: apps/v1
kind: Deployment

metadata:
  name: client-deployment

spec:
  replicas: 1

  selector:
    matchLabels:
      component: client

  template:
    metadata:
      labels:
        component: client

    spec:
      containers:
        - name: client
          image: akashhulke/client:2ef9ad6d14e84adf977c3029f2fb9b5fe68fdd6c
          ports:
            - containerPort: 3000