apiVersion: apps/v1
kind: Deployment

metadata:
  name: nginx-deployment

spec:
  replicas: 1

  selector:
    matchLabels:
      component: nginx

  template:
    metadata:
      labels:
        component: nginx

    spec:
      containers:
        - name: nginx
          image: akashhulke/nginx:45b6457dc2672586aa87d59dd2765cb971518921

          ports:
            - containerPort: 80