apiVersion: apps/v1
kind: Deployment

metadata:
  name: nginx-deployment

spec:
  replicas: 1

  selector:
    matchLabels:
      component: nginx

  template:
    metadata:
      labels:
        component: nginx

    spec:
      containers:
        - name: nginx
          image: akashhulke/nginx:ba2a0458685391c10b6183721c2ac105bcca524b

          ports:
            - containerPort: 80