apiVersion: apps/v1
kind: Deployment

metadata:
  name: nginx-deployment

spec:
  replicas: 1

  selector:
    matchLabels:
      component: nginx

  template:
    metadata:
      labels:
        component: nginx

    spec:
      containers:
        - name: nginx
          image: akashhulke/nginx:40ae81ccdb80d841c8db6a7bd2423fec11dbfba7

          ports:
            - containerPort: 80