apiVersion: apps/v1
kind: Deployment

metadata:
  name: worker-deployment

spec:
  replicas: 1

  selector:
    matchLabels:
      component: worker

  template:
    metadata:
      labels:
        component: worker

    spec:
      containers:
        - name: worker
          image: akashhulke/worker:c2a1b99d256586e629b5a48b37028802f3571e49