apiVersion: apps/v1
kind: Deployment

metadata:
  name: worker-deployment

spec:
  replicas: 1

  selector:
    matchLabels:
      component: worker

  template:
    metadata:
      labels:
        component: worker

    spec:
      containers:
        - name: worker
          image: akashhulke/worker:2efa79e8aa8cbb1bb1c139aa738be9c78c910d54

          env:
            - name: REDIS_HOST
              value: redis-service

            - name: REDIS_PORT
              value: "6379"