apiVersion: apps/v1
kind: Deployment

metadata:
  name: worker-deployment

spec:
  replicas: 1

  selector:
    matchLabels:
      component: worker

  template:
    metadata:
      labels:
        component: worker

    spec:
      containers:
        - name: worker
          image: akashhulke/worker:2ef9ad6d14e84adf977c3029f2fb9b5fe68fdd6c